-- CreateTable
CREATE TABLE `RepairReceipt` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `receiptNo` VARCHAR(191) NULL,
    `docDate` DATETIME(3) NOT NULL,
    `status` ENUM('RECEIVED', 'REPAIRING', 'FOREIGN_CONTACT', 'QUOTATION', 'APPROVED', 'WAITING_PART', 'WAITING_CLAIM', 'DONE', 'CANCELLED') NOT NULL,
    `customer` VARCHAR(100) NOT NULL,
    `department` VARCHAR(100) NOT NULL,
    `deviceName` VARCHAR(100) NULL,
    `brand` VARCHAR(100) NOT NULL,
    `model` VARCHAR(100) NULL,
    `serial` VARCHAR(100) NULL,
    `assetNo` VARCHAR(100) NULL,
    `symptom` TEXT NULL,
    `inWarranty` BOOLEAN NOT NULL DEFAULT false,
    `outWarranty` BOOLEAN NOT NULL DEFAULT false,
    `reporterName` VARCHAR(100) NULL,
    `reporterPhone` VARCHAR(50) NULL,
    `responsible1` VARCHAR(100) NULL,
    `responsible2` VARCHAR(100) NULL,
    `sender` VARCHAR(100) NULL,
    `senderNumber` VARCHAR(50) NULL,
    `accessories` TEXT NULL,
    `note` TEXT NULL,
    `serviceWorkshop` BOOLEAN NOT NULL DEFAULT false,
    `serviceWorkshopDate` DATETIME(3) NULL,
    `serviceOnsite` BOOLEAN NOT NULL DEFAULT false,
    `serviceOnsiteDate` DATETIME(3) NULL,
    `serviceExternal` BOOLEAN NOT NULL DEFAULT false,
    `serviceExternalCompany` VARCHAR(100) NULL,
    `serviceExternalDate` DATETIME(3) NULL,
    `stUsable` BOOLEAN NOT NULL DEFAULT false,
    `stReturn` BOOLEAN NOT NULL DEFAULT false,
    `quoteNo` VARCHAR(100) NULL,
    `responsibleTechName` VARCHAR(100) NULL,
    `inspectorName` VARCHAR(100) NULL,
    `returnDate` DATETIME(3) NULL,
    `quotationApproved` BOOLEAN NOT NULL DEFAULT false,
    `quotationRejected` BOOLEAN NOT NULL DEFAULT false,
    `quotationNotRequired` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `RepairReceipt_receiptNo_key`(`receiptNo`),
    INDEX `RepairReceipt_receiptNo_idx`(`receiptNo`),
    INDEX `RepairReceipt_docDate_idx`(`docDate`),
    INDEX `RepairReceipt_status_idx`(`status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
